_AI_LIST_v3 = [
    'generative ai',
    'large language model',
    '(llm)',
    ' llm',
    'a.i.',
    'ai/ml',
    'aiml',
    'artificial intelligence',
    'machine learning',
    'computer vision',
    'natural language processing',
    ' nlp ',
    'kernel method',
    'kernel methods',
    'xgboost',
    'sentiment classification',
    'long short term memory',
    'long short-term memory',
    'lstm',
    'neutral network',
    'supervised learning',
    'unsupervised learning',
    'word2vec',
    'deep learning',
    'natural language toolkit',
    'latent semantic analysis',
    'stochastic gradient descent',
    'dimensionality reduction',
    'chatbot',
    'recommender system',
    'random forest',
    'support vector machine',
    'markov model',
    'computational linguistic',
    'clustering algorithms',
    'matrix factorization',
    'object recognition',
    'classification algorithm',
    'information extraction',
    'image recognition',
    'bayesian networks',
    'data mining',
    'data science',
    'data scientist',
    'machine translation',
    'business intelligence',
    'big data',
    'hadoop',


    'financial forecasting',
    'regression analysis',
    'time series analysis',
    'algorithmic trading',
    'data augmentation',
    'GPT',
]
